### PR TITLE
Renaming sources/folders/namespaces/etc

### PR DESCRIPTION
**Pull request by pjanotti**
Renaming sources/folders/namespaces/etc, basically removing the Terrajobst "brand" 😛

`Terrajobst.PlatformCompat` to `ApiCompat`
`Terrajobst` to `ApiCompat`

Renamed nugget references but not ready to publish it yet.

Opportunistic fix: change `build.cmd`

### CODE REVIEW

**Comment by mellinoe** [comment]
ApiCompat is a different thing -- should we still call it PlatformCompat?

**Comment by pjanotti** [comment]
PlatformCompat implies something like OS for me and while this is basically where this is starting (i.e.: main target for now) there are also deprecation that is not necessarily platform related. In that sense ApiCompat seems a more broad term. Good naming is always hard...

**Comment by mellinoe** [comment]
I guess the name is a little bit closer to what we want, but deprecation is also a different topic from API compatibility in genenral.

I mostly just meant that the name is already in use for our [ApiCompat tool](https://github.com/dotnet/buildtools/tree/master/src/ApiCompat). It might be confusing to use the same name here.

**Comment by pjanotti** [comment]
Yes, compatibility is less general than what we want to cover. If I am seeing this right the ApiCompat tool is intended to be used in corefx builds not directly by people creating their on projects, that said it will be good to avoid the conflict. @karelz any suggestions? Some alternatives: ApiCheck, ApiAdvisor, NetApiAdvisor...

**Comment by jnm2** [comment]
Platform doesn't primarily mean OS. It means runtime or BCL, right?
Some of these *are* OS-specific as well as some that are runtime-specific.

Previous conversation: https://github.com/dotnet/platform-compat/issues/16

**Comment by pjanotti** [comment]
Ok, you guys convinced me: the most voted candidate so far is PlatformCompat. I will let this sit here for a bit so other people can jump in before I redo it (and perhaps convince me otherwise!):

`Terrajobst.PlatformCompat` to `PlatformCompat`
`Terrajobs` to `PlatformCompat`

**Pull request merged**
